version: "3"
services:
  mysql-standalone:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=db_gym
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/db_gym?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone